### PR TITLE
Fix twitter cta Link

### PR DESCRIPTION
**Pull request by pieromqwerty**
Uses https://twitter.com/intent/follow?screen_name=replit instead of https://twitter.com/replit

### CODE REVIEW

**Comment by pieromqwerty** [comment]
also ignore all of the commits on my branch, my git went :/

**Comment by ykdojo** [comment]
looks good!

**Review by sergeichestakov — APPROVED** [review]
🆒 don't be afraid to approve @ykdojo 😄

**Comment by ykdojo** [comment]
@sergeichestakov yeah I was trying to approve but couldn't find the button lol

**Pull request merged**
